config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: 'oauth/applications'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'
  post 'users' => 'users#create'
  get 'pages/:name' => 'pages#show', as: :page
  resources :users, only: :create do
    collection do
      get 'edit' => 'users#edit'
      put 'save' => 'users#update'
      patch 'save' => 'users#update'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get 'me' => 'users#me', on: :collection
        get ':email' => 'users#show', on: :collection
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_application.rb
class ClientApplication < Doorkeeper::Application
  has_many :footprints, foreign_key: :application_id, dependent: :destroy
  validates :user_update_url, url: true, allow_nil: true, allow_blank: true
end

app/models/footprint.rb
class Footprint < ApplicationRecord
  belongs_to :user
  belongs_to :application, class_name: 'ClientApplication'

  validates :user_id, :application_id, presence: true
  validates :user_id, uniqueness: [ :application_id ]
end

app/models/user.rb
class User < ApplicationRecord
  TRACKED_ATTRS = ['first_name', 'last_name', 'full_name', 'email']
  include Clearance::User

  has_many :oauth_applications, class_name: 'ClientApplication', as: :owner, dependent: :destroy
  has_many :footprints, dependent: :destroy
  validates :first_name, :last_name, :full_name, presence: true
  after_update :send_user_update_callbacks, if: :changed?

  private

  def send_user_update_callbacks
    tracked_changes = changes.select { |k,v| TRACKED_ATTRS.include? k }

    if tracked_changes.any?
      SetupWalkThroughFootprintsJob.perform_async(id, tracked_changes)
    end
  end
end

app/controllers/api/v1/api_controller.rb
class API::V1::ApiController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :doorkeeper_authorize!

  private

  def record_not_found
    render json: { error: 'Not Found' }, status: :not_found
  end
end

app/controllers/api/v1/application_controller.rb
class API::V1::ApplicationController < ActionController::API
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  before_action :doorkeeper_authorize!

  private

  def record_not_found
    render json: { error: 'Not Found' }, status: :not_found
  end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < API::V1::ApiController
  after_action :create_footprint

  def index
    @users = User.all
    render json: @users
  end

  def me
    @user = current_resource_owner
    render json: @user
  end

  def show
    encoded_email = Base64.urlsafe_decode64(params[:email])
    @user = User.find_by!(email: encoded_email)
    render json: @user
  rescue ArgumentError
    render json: { error: 'Wrong base64 format' }
  end

  private

  def current_resource_owner
    User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end

  def create_footprint
    Footprint.find_or_create_by!(
      user: @user,
      application_id: doorkeeper_token.application_id
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/oauth/applications_controller.rb
class Oauth::ApplicationsController < Doorkeeper::ApplicationsController
  include Clearance::Controller
  layout 'application'
  before_action :require_login

  def index
    @applications = current_user.oauth_applications.select(:id, :name)
  end

  def new
    @application = ClientApplication.new
  end

  def create
    @application = ClientApplication.new(application_params)
    @application.owner = current_user if Doorkeeper.configuration.confirm_application_owner?
    if @application.save
      flash[:notice] = I18n.t(:notice, :scope => [:doorkeeper, :flash, :applications, :create])
      redirect_to oauth_application_url(@application)
    else
      render :new
    end
  end

  private

  def set_application
    @application = current_user.oauth_applications.find(params[:id])
  end

  def application_params
    params.require(:client_application).permit(:name, :redirect_uri, :scopes, :user_update_url)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    path = File.join(Rails.root, "#{params[:name]}.md")
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    render inline: markdown.render(File.read(path)), layout: 'application'
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  before_action :require_login, only: [:edit, :update]

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash[:notice] = 'Saved successfully'
    end

    render :edit
  end

  private

  def user_from_params
    Clearance.configuration.user_model.new(user_params)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :full_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages
    flash.map do |key, message|
      content_tag :div, message, class: "alert alert-#{flash_name_to_bootstrap(key)}"
    end.join.html_safe
  end

  private

  def flash_name_to_bootstrap(name)
    case name
    when 'error'
      'danger'
    when 'notice'
      'success'
    else
      name
    end
  end
end

app/views/doorkeeper/applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag t('doorkeeper.applications.buttons.destroy'), onclick: "return confirm('#{ t('doorkeeper.applications.confirmations.destroy') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/applications/_form.html.erb
<%= form_for application, url: doorkeeper_submit_path(application), html: {class: 'form-horizontal', role: 'form'} do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p><%= t('doorkeeper.applications.form.error') %></p></div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:name].present?}" do %>
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :name %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:redirect_uri].present?}" do %>
    <%= f.label :redirect_uri, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :redirect_uri, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :redirect_uri %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.redirect_uri') %>
      </span>
      <% if Doorkeeper.configuration.native_redirect_uri %>
          <span class="help-block">
            <%= raw t('doorkeeper.applications.help.native_redirect_uri', native_redirect_uri: "<code>#{ Doorkeeper.configuration.native_redirect_uri }</code>") %>
          </span>
      <% end %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:user_update_url].present?}" do %>
    <%= f.label :user_update_url, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :user_update_url, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :user_update_url %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.user_update_url') %>
      </span>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:scopes].present?}" do %>
    <%= f.label :scopes, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :scopes, class: 'form-control' %>
      <%= doorkeeper_errors_for application, :scopes %>
      <span class="help-block">
        <%= t('doorkeeper.applications.help.scopes') %>
      </span>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit t('doorkeeper.applications.buttons.submit'), class: "btn btn-primary" %>
      <%= link_to t('doorkeeper.applications.buttons.cancel'), oauth_applications_path, :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/doorkeeper/applications/edit.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/index.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<p><%= link_to t('.new'), new_oauth_application_path, class: 'btn btn-success' %></p>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('.name') %></th>
    <th><%= t('.callback_url') %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @applications.each do |application| %>
    <tr id="application_<%= application.id %>">
      <td><%= link_to application.name, oauth_application_path(application) %></td>
      <td><%= application.redirect_uri %></td>
      <td><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(application), class: 'btn btn-link' %></td>
      <td><%= render 'delete_form', application: application %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/doorkeeper/applications/new.html.erb
<div class="page-header">
  <h1><%= t('.title') %></h1>
</div>

<%= render 'form', application: @application %>

app/views/doorkeeper/applications/show.html.erb
<div class="page-header">
  <h1><%= t('.title', name: @application.name) %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4><%= t('.application_id') %>:</h4>
    <p><code id="application_id"><%= @application.uid %></code></p>

    <h4><%= t('.secret') %>:</h4>
    <p><code id="secret"><%= @application.secret %></code></p>

    <h4><%= t('.scopes') %>:</h4>
    <p><code id="scopes"><%= @application.scopes %></code></p>

    <h4><%= t('.callback_urls') %>:</h4>

    <table>
      <% @application.redirect_uri.split.each do |uri| %>
        <tr>
          <td>
            <code><%= uri %></code>
          </td>
          <td>
            <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'btn btn-success', target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <h3><%= t('.actions') %></h3>

    <p><%= link_to t('doorkeeper.applications.buttons.edit'), edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>

app/views/doorkeeper/authorizations/error.html.erb
<div class="page-header">
  <h1><%= t('doorkeeper.authorizations.error.title') %></h1>
</div>

<main role="main">
  <pre><%= @pre_auth.error_response.body[:error_description] %></pre>
</main>

app/views/doorkeeper/authorizations/new.html.erb
<header class="page-header" role="banner">
  <h1><%= t('.title') %></h1>
</header>

<main role="main">
  <p class="h4">
    <%= raw t('.prompt', client_name: "<strong class=\"text-info\">#{ @pre_auth.client.name }</strong>") %>
  </p>

  <% if @pre_auth.scopes.count > 0 %>
    <div id="oauth-permissions">
      <p><%= t('.able_to') %>:</p>

      <ul class="text-info">
        <% @pre_auth.scopes.each do |scope| %>
          <li><%= t scope, scope: [:doorkeeper, :scopes] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_tag oauth_authorization_path, method: :post do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.authorize'), class: "btn btn-success btn-lg btn-block" %>
    <% end %>
    <%= form_tag oauth_authorization_path, method: :delete do %>
      <%= hidden_field_tag :client_id, @pre_auth.client.uid %>
      <%= hidden_field_tag :redirect_uri, @pre_auth.redirect_uri %>
      <%= hidden_field_tag :state, @pre_auth.state %>
      <%= hidden_field_tag :response_type, @pre_auth.response_type %>
      <%= hidden_field_tag :scope, @pre_auth.scope %>
      <%= submit_tag t('doorkeeper.authorizations.buttons.deny'), class: "btn btn-danger btn-lg btn-block" %>
    <% end %>
  </div>
</main>

app/views/doorkeeper/authorizations/show.html.erb
<header class="page-header">
  <h1><%= t('.title') %>:</h1>
</header>

<main role="main">
  <code id="authorization_code"><%= params[:code] %></code>
</main>

app/views/doorkeeper/authorized_applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_authorized_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag t('doorkeeper.authorized_applications.buttons.revoke'), onclick: "return confirm('#{ t('doorkeeper.authorized_applications.confirmations.revoke') }')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/authorized_applications/index.html.erb
<header class="page-header">
  <h1><%= t('doorkeeper.authorized_applications.index.title') %></h1>
</header>

<main role="main">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= t('doorkeeper.authorized_applications.index.application') %></th>
      <th><%= t('doorkeeper.authorized_applications.index.created_at') %></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.name %></td>
        <td><%= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
        <td><%= render 'delete_form', application: application %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gravatar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
       <div class="header clearfix">
         <nav>
           <ul class="nav nav-pills pull-right">
             <% if signed_in? %>
               <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages <span class="caret"></span></a>
                 <ul class="dropdown-menu">
                   <li><%= link_to 'README', page_path("README") %></li>
                   <li><%= link_to 'SCALEME', page_path("SCALEME") %></li>
                 </ul>
               </li>
               <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.full_name %> <span class="caret"></span></a>
                 <ul class="dropdown-menu">
                   <li><%= link_to 'My profile', edit_users_path %></li>
                   <li><%= link_to 'My Apps', oauth_applications_path %></li>
                   <li role="separator" class="divider"></li>
                   <li><%= link_to 'Log out', sign_out_path, method: :delete %></li>
                 </ul>
               </li>
             <% else %>
               <li role="presentation"><%= link_to 'Log in', sign_in_path %></li>
               <li role="presentation"><%= link_to 'Sign up', sign_up_path %></li>
             <% end %>
           </ul>
         </nav>
         <h3 class="text-muted"><a href='/'>GravaClone</a></h3>
       </div>

       <%= yield %>

       <footer class="footer">
         <p>&copy; 2016 Company, Inc.</p>
       </footer>

     </div> <!-- /container -->
  </body>
</html>

app/views/layouts/doorkeeper/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doorkeeper</title>
  <%= stylesheet_link_tag "doorkeeper/admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t('doorkeeper.layouts.admin.nav.oauth2_provider'), oauth_applications_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav">
      <%= content_tag :li, class: "#{'active' if request.path == oauth_applications_path}" do %>
        <%= link_to t('doorkeeper.layouts.admin.nav.applications'), oauth_applications_path %>
      <% end %>
      <%= content_tag :li do %>
        <%= link_to t('doorkeeper.layouts.admin.nav.home'), root_path %>
      <% end %>
    </ul>
  </div>
</div>
<div class="container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/doorkeeper/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('doorkeeper.layouts.application.title') %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag "doorkeeper/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
  <%- if flash[:notice].present? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
  <% end -%>

  <%= yield %>
</div>
</body>
</html>

app/views/oauth/applications/index.html.erb
<% if @applications.any? %>
  <h3 class="text-center"><%= t(".title") %></h3>

  <div class="row">
    <% @applications.each do |application| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to application.name, oauth_application_path(application) %>
            <div class="btn-group btn-group-xs pull-right" role="group" >
              <%= link_to 'Edit', edit_oauth_application_path(application), class: 'btn btn-primary' %>
              <%= link_to 'Destroy', oauth_application_path(application), class: 'btn btn-danger', method: :destroy %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="jumbotron">
    <h1>It is no apps, for now :(</h1>
    <p class="lead">Try to add application to be able to send requests to api and authenticate users with our service.</p>
    <p><%= link_to 'Add new app', new_oauth_application_path, class: 'btn btn-lg btn-success'%></p>
  </div>
<% end %>

app/views/oauth/applications/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= @application.name %>
        <div class="btn-group btn-group-xs pull-right" role="group" >
          <%= link_to 'Edit', edit_oauth_application_path(@application), class: 'btn btn-primary' %>
          <%= link_to 'Destroy', oauth_application_path(@application), class: 'btn btn-danger', method: :delete %>
        </div>
      </div>
      <div class="panel-body">
        <h4><%= t('.basic_info') %></h4>
        <ul class="list-group">
          <li class="list-group-item">
            <code class="pull-right"><%= @application.uid %></code>
            <%= t('.application_id') %>
          </li>
          <li class="list-group-item">
            <code class="pull-right"><%= @application.secret %></code>
            <%= t('.secret') %>
          </li>
          <li class="list-group-item">
            <code class="pull-right"><%= @application.user_update_url %></code>
            <%= t('.user_update_url') %>
          </li>
          <li class="list-group-item">
            <code class="pull-right"><%= @application.scopes %></code>
            <%= t('.scopes') %>
          </li>
        </ul>
        <hr>
        <h4><%= t('.callback_urls') %></h4>
        <ul class="list-group">
          <% @application.redirect_uri.split.each do |uri| %>
            <li class="list-group-item">
              <%= link_to t('doorkeeper.applications.buttons.authorize'), oauth_authorization_path(client_id: @application.uid, redirect_uri: uri, response_type: 'code', scope: @application.scopes), class: 'pull-right btn btn-xs btn-success', target: '_blank' %>
              <code><%= uri %></code>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
  <%= form.text_field :first_name %>
  <%= form.text_field :last_name %>
  <%= form.text_field :full_name %>
  <%= form.email_field :email, value: form.object.email %>
  <%= form.password_field :password %>
  <%= form.submit %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="text-center"><%= t(".title") %></h3>
        <%= flash_messages %>
        <%= bootstrap_form_for @user, { url: save_users_path, method: :patch, label_errors: true } do |form| %>
          <%= render partial: '/users/form', object: form %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <h3 class="text-center"><%= t(".title") %></h3>
        <%= flash_messages %>
        <%= bootstrap_form_for @user, label_errors: true do |form| %>
          <%= render partial: '/users/form', object: form %>
        <% end %>
      </div>
    </div>
  </div>
</div>